name: Links Checker

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1,15 * *" # twice a month

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0

      - name: Create Issue for Broken Links
        if: ${{ failure() }}
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: 'Bug: Found Broken Link (help wanted)'
          content-filepath: './lychee/out.md'
          labels: 'report, automated issue, good first issue'
